# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clustering.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(791, 525)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(20, 60, 761, 421))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(380, 20, 91, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(340, 490, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "1"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "2"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "3"))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", "4"))
        item = self.listWidget.item(4)
        item.setText(_translate("Form", "5"))
        item = self.listWidget.item(5)
        item.setText(_translate("Form", "6"))
        item = self.listWidget.item(6)
        item.setText(_translate("Form", "7"))
        item = self.listWidget.item(7)
        item.setText(_translate("Form", "8"))
        item = self.listWidget.item(8)
        item.setText(_translate("Form", "9"))
        item = self.listWidget.item(9)
        item.setText(_translate("Form", "10"))
        item = self.listWidget.item(10)
        item.setText(_translate("Form", "11"))
        item = self.listWidget.item(11)
        item.setText(_translate("Form", "12"))
        item = self.listWidget.item(12)
        item.setText(_translate("Form", "13"))
        item = self.listWidget.item(13)
        item.setText(_translate("Form", "14"))
        item = self.listWidget.item(14)
        item.setText(_translate("Form", "15"))
        item = self.listWidget.item(15)
        item.setText(_translate("Form", "16"))
        item = self.listWidget.item(16)
        item.setText(_translate("Form", "17"))
        item = self.listWidget.item(17)
        item.setText(_translate("Form", "18"))
        item = self.listWidget.item(18)
        item.setText(_translate("Form", "19"))
        item = self.listWidget.item(19)
        item.setText(_translate("Form", "20"))
        item = self.listWidget.item(20)
        item.setText(_translate("Form", "21"))
        item = self.listWidget.item(21)
        item.setText(_translate("Form", "22"))
        item = self.listWidget.item(22)
        item.setText(_translate("Form", "23"))
        item = self.listWidget.item(23)
        item.setText(_translate("Form", "24"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form", "聚类结果"))
        self.pushButton.setText(_translate("Form", "聚类评估"))
