# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'office_stat.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(893, 838)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(50, 70, 231, 621))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        self.tableWidget1 = QtWidgets.QTableWidget(Form)
        self.tableWidget1.setGeometry(QtCore.QRect(330, 70, 231, 621))
        self.tableWidget1.setObjectName("tableWidget1")
        self.tableWidget1.setColumnCount(2)
        self.tableWidget1.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setItem(3, 1, item)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 30, 171, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(370, 30, 161, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(670, 30, 181, 16))
        self.label_3.setObjectName("label_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(Form)
        self.tableWidget_2.setGeometry(QtCore.QRect(630, 70, 231, 621))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 1, item)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(100, 740, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 740, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(720, 740, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "共享型办公室"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "频率"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "design"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "0.70163"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "furniture"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "0.48019"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget1.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget1.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget1.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget1.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget1.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget1.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget1.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget1.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget1.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget1.verticalHeaderItem(9)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget1.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget1.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget1.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget1.verticalHeaderItem(13)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget1.verticalHeaderItem(14)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget1.horizontalHeaderItem(0)
        item.setText(_translate("Form", "开放式办公室"))
        item = self.tableWidget1.horizontalHeaderItem(1)
        item.setText(_translate("Form", "频率"))
        __sortingEnabled = self.tableWidget1.isSortingEnabled()
        self.tableWidget1.setSortingEnabled(False)
        item = self.tableWidget1.item(0, 0)
        item.setText(_translate("Form", "design"))
        item = self.tableWidget1.item(0, 1)
        item.setText(_translate("Form", "0.75562"))
        item = self.tableWidget1.item(1, 0)
        item.setText(_translate("Form", "office"))
        item = self.tableWidget1.item(1, 1)
        item.setText(_translate("Form", "0.61236"))
        item = self.tableWidget1.item(2, 0)
        item.setText(_translate("Form", "furniture"))
        item = self.tableWidget1.item(2, 1)
        item.setText(_translate("Form", "0.39326"))
        item = self.tableWidget1.item(3, 0)
        item.setText(_translate("Form", "ceiling"))
        item = self.tableWidget1.item(3, 1)
        item.setText(_translate("Form", "0.36517"))
        self.tableWidget1.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form", "共享型办公室图像标签统计"))
        self.label_2.setText(_translate("Form", "开放式办公室图像标签统计"))
        self.label_3.setText(_translate("Form", "办公室总图像数据集标签统计"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget_2.verticalHeaderItem(14)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "总数据集标签"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "频率"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("Form", "design"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("Form", "0.71333"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("Form", "furniture"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("Form", "0.46135"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("Form", "table"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("Form", "0.36884"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("Form", "office"))
        item = self.tableWidget_2.item(3, 1)
        item.setText(_translate("Form", "0.36093"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("Form", "可视化"))
        self.pushButton_2.setText(_translate("Form", "可视化"))
        self.pushButton_3.setText(_translate("Form", "可视化"))
